version: '3.8'

x-base-config: &base-config
  networks:
    - homelabnetwork
  env_file: !reset []  # Remove env_file
  environment:  # Completely replace environment section
    - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}

networks:
  homelabnetwork:
    external: true
